server:
  port: 8082

spring:
  application:

    name: user-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:264246243864-5ojqq2rj6ma33sououb45uc8e5da8o2f.apps.googleusercontent.com}
  datasource:

    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/userdb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
